# Stage 1: Build
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the application source code
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine

# Copy the build output to the Nginx HTML directory
COPY --from=build /usr/src/app/build /var/www/fe/html

# Copy the custom Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 1444 to the outside world
EXPOSE 1444

# Command to run Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]