
export const PLAY_AGAIN = "PLAY_AGAIN";
export const PLAY_AGAIN_ACCEPT = "PLAY_AGAIN_ACCEPT";
export const PLAY_AGAIN_REJECT = "PLAY_AGAIN_REJECT";
export const PLAY_AGAIN_CANCEL = "PLAY_AGAIN_CANCEL";
export const PLAY_AGAIN_TIMEOUT = "PLAY_AGAIN_TIMEOUT";
export const PLAY_AGAIN_ERROR = "PLAY_AGAIN_ERROR";

